version: "3.9"

services:
  # -------------------------------
  # Frontend
  # -------------------------------
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    image: zenvy-client:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1

  # -------------------------------
  # Backend
  # -------------------------------
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    image: zenvy-server:latest
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: zenvy-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl/certs

  # -------------------------------
  # Redis
  # -------------------------------
  redis:
    image: redis:7.2-alpine
    container_name: zenvy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # -------------------------------
  # ChromaDB
  # -------------------------------
  chromadb:
    image: chromadb/chroma:latest
    container_name: zenvy-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE

# -------------------------------
# Volumes
# -------------------------------
volumes:
  redis_data:
  chromadb_data:
