import mongoose from 'mongoose';
import { User } from '../database/auth/auth';
import { faker } from '@faker-js/faker';
import dotenv from 'dotenv';
import path from 'path';
import bcrypt from 'bcrypt';
import fs from 'fs';

// Load environment variables
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const USER_COUNT = 200;
const CSV_FILE = 'dummy_users.csv';

const seedUsers = async () => {
  try {
    // Connect to MongoDB
    console.log('Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/project_zenvy');
    console.log('Connected!');

    console.log(`Generating ${USER_COUNT} dummy users...`);

    const users = [];
    const csvRows = ['email,password,firstName,lastName,role']; // CSV Header

    // We'll use a fixed password for simplicity, or generate random ones. 
    // Let's generate random ones but keep track of them.
    // Actually, hashing 200 times might take a few seconds.

    // Pre-calculate hash for "Password123!" to speed up if we wanted uniform passwords,
    // but specific credentials requested implies we should track them.
    // I'll hash individually or use a common one. 
    // To make it realistic, I'll use a common password but save it in CSV so user knows.
    // Wait, "each user will be saved into a csv file".
    
    for (let i = 0; i < USER_COUNT; i++) {
        const firstName = faker.person.firstName();
        const lastName = faker.person.lastName();
        const email = faker.internet.email({ firstName, lastName, provider: 'zenvy.test' }).toLowerCase();
        const passwordPlain = 'Password123!'; // Default password for all dummy users
        
        // Hash password
        const BCRYPT_ROUNDS = parseInt(process.env.BCRYPT_ROUNDS || '8');
        const hashedPassword = await bcrypt.hash(passwordPlain, BCRYPT_ROUNDS);

        const user = {
            firstName,
            lastName,
            email,
            password: hashedPassword,
            role: 'user',
            emailVerified: true,
            onboardingCompleted: true,
            authProvider: 'local',
            // Add other required fields if any (schema defaults handle most)
            // widgetId will be auto-generated by pre-save hook?
            // User schema has pre-save hook commented out in the file I saw?
            // server/src/database/schema/User.ts:176 is commented out.
            // If so, we might need to verify if widgetId is required. 
            // It says: widgetId: { type: String, unique: true, sparse: true, index: true }
            // sparse: true means null is allowed/ignored for uniqueness. 
            // So we can leave it undefined.
        };

        users.push(user);
        csvRows.push(`${email},${passwordPlain},${firstName},${lastName},user`);
    }

    // Insert into DB
    console.log('Inserting users into database...');
    await User.insertMany(users);
    console.log(`Successfully created ${users.length} users.`);

    // Write CSV
    const csvContent = csvRows.join('\n');
    const outputPath = path.resolve(__dirname, `../../${CSV_FILE}`);
    fs.writeFileSync(outputPath, csvContent);
    console.log(`User credentials saved to: ${outputPath}`);

  } catch (error) {
    console.error('Error seeding users:', error);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  }
};

seedUsers();
